import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (name) => readFile(path.join(root, name), 'utf8')
const exists = async (name) => access(path.join(root, name)).then(() => true, () => false)

test('the public product identity is DSH-Portable everywhere users see it', async () => {
  const manifest = JSON.parse(await read('package.json'))
  assert.equal(manifest.name, 'dsh-portable')
  assert.match(manifest.version, /^0\.1\.0-rc\.6-portable\.\d+$/)

  const chineseReadme = await read('README.md')
  const englishReadme = await read('README.en.md')
  const userReadme = await read('templates/USER-README.txt')
  const combined = `${chineseReadme}\n${englishReadme}\n${userReadme}`
  assert.match(chineseReadme, /<h1 align="center">DSH-Portable<\/h1>/)
  assert.match(englishReadme, /<h1 align="center">DSH-Portable<\/h1>/)
  assert.match(userReadme, /^DSH-Portable$/m)
  assert.doesNotMatch(combined, /DeepSeek Harness Windows Portable|community\.1|Unofficial community packaging/i)
  assert.doesNotMatch(userReadme, /reviewed commit|build script|npm lock|promotion|development history/i)
})

test('the GitHub landing page gives beginners one obvious download path', async () => {
  const chineseReadme = await read('README.md')
  const englishReadme = await read('README.en.md')
  const recommendedUrl = 'https://github.com/WSL043/DSH-Portable/releases/latest/download/DSH-Portable-windows-x64.exe'

  assert.match(chineseReadme, /<img[^>]+assets\/DSH-Portable\.svg[^>]+alt="DeepSeek Harness"/i)
  assert.match(englishReadme, /Start in 3 steps/i)
  assert.match(chineseReadme, /三步启动/)
  assert.match(englishReadme, new RegExp(recommendedUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  assert.match(chineseReadme, new RegExp(recommendedUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  assert.ok(chineseReadme.indexOf(recommendedUrl) < chineseReadme.indexOf('<details>'), 'the recommended download must appear before advanced choices')
  assert.doesNotMatch(englishReadme.slice(0, englishReadme.indexOf('<details>')), /\|\s*Download\s*\|\s*Use case\s*\|/i)
  assert.doesNotMatch(englishReadme, /Each release includes a `\.sha256` file/i)
})

test('Simplified Chinese is the default GitHub landing page and English is a complete peer', async () => {
  const chinese = await read('README.md')
  const english = await read('README.en.md')
  assert.equal(await exists('README.zh-CN.md'), false)
  assert.match(chinese.slice(0, 1400), /<strong>简体中文<\/strong>.+README\.en\.md/s)
  assert.match(english.slice(0, 1400), /README\.md.+<strong>English<\/strong>/s)
  assert.equal((english.match(/assets\/dsh-interface\.png/g) || []).length, 1)
  assert.equal((chinese.match(/assets\/dsh-interface\.png/g) || []).length, 1)
  for (const heading of ['Start in 3 steps', 'Portable data', 'Updates', 'Security']) assert.match(english, new RegExp(`## ${heading}`, 'i'))
  for (const heading of ['三步启动', '便携数据', '更新', '安全']) assert.match(chinese, new RegExp(`## ${heading}`))
  assert.doesNotMatch(english, /三步启动|下载 Windows|便携数据与安全/)
})

test('release notes prioritize downloads and keep verification optional', async () => {
  const notes = await read('templates/RELEASE-NOTES.md')
  assert.match(notes, /^>\s+打包官方 DeepSeek Harness 预览版/m)
  assert.doesNotMatch(notes, /^#\s+DSH-Portable/m)
  assert.match(notes, /DSH-Portable-windows-x64\.exe/)
  assert.ok(notes.indexOf('DSH-Portable-windows-x64.exe') < notes.indexOf('<details>'))
  assert.doesNotMatch(notes, /\b[a-f0-9]{64}\b/i)
  assert.equal((notes.match(/SHA256SUMS|\b[a-f0-9]{64}\b/gi) || []).length, 0)
})

test('desktop icons are derived from the pinned official DSH mark', async () => {
  const provenance = JSON.parse(await read('assets/BRAND-ASSETS.json'))
  assert.deepEqual(provenance.source, {
    repository: 'https://github.com/deepseek-ai/deepseek-harness',
    commit: '47f943859bef60e4160492346772ded9b24f765a',
    path: 'apps/web/public/favicon.svg',
    gitBlob: 'c92f15d43b4e12aafac4e09728db9696384b6b99',
  })
  assert.deepEqual(provenance.appIconTheme, { light: '#000000', dark: '#FFFFFF' })
  assert.match(provenance.derivation, /official application favicon geometry and adaptive theme/i)

  const svg = await read('assets/DSH-Portable.svg')
  const renderer = await read('scripts/render-icons.mjs')
  assert.match(svg, /viewBox="0 0 50 50"/)
  assert.match(svg, /path\s*\{\s*fill:\s*#fff;/)
  assert.match(svg, /fill="#000"/)
  assert.doesNotMatch(svg, /#4D6BFE/i)
  assert.match(renderer, /flatten\(\{\s*background:\s*['"]#fff['"]\s*\}\)/)
  assert.equal(await exists('assets/DSH-Portable.ico'), true)
  assert.equal(await exists('assets/DSH-Portable.icns'), true)
})

test('Windows package exposes real GUI executables with matching icon and no path install', async () => {
  const source = await read('launcher/windows/DSH-Portable.cs')
  const bootstrap = await read('launcher/windows/DSH-Bootstrap.cs')
  const manifest = await read('launcher/windows/DSH-Portable.manifest')
  const build = await read('scripts/build-windows.ps1')

  assert.match(source, /Application\.ExecutablePath/)
  assert.match(source, /portable-cli\.mjs/)
  assert.match(source, /Icon\.ExtractAssociatedIcon/)
  assert.match(source, /nonInteractive/)
  assert.match(source, /Environment\.ExitCode/)
  assert.match(source, /DSH_PORTABLE_LAUNCHER_DIAGNOSTIC/)
  assert.match(source, /StandardOutputEncoding\s*=\s*Encoding\.UTF8/)
  assert.match(source, /StandardErrorEncoding\s*=\s*Encoding\.UTF8/)
  assert.match(source, /new TextBox\(\)/)
  assert.match(source, /ScrollBars\.Vertical/)
  assert.match(source, /try\s*\{\s*Clipboard\.SetText/s)
  assert.match(source, /IsStopCommand\(launcherArgs\)[\s\S]+could not stop[\s\S]+could not start/)
  assert.match(source, /CancelButton\s*=\s*closeButton/)
  assert.doesNotMatch(source, /AppData|Program Files|USERPROFILE/i)
  assert.match(manifest, /requestedExecutionLevel level="asInvoker"/)
  assert.match(manifest, /longPathAware[^>]*>true</)
  assert.match(build, /target:winexe/i)
  assert.match(build, /win32icon/i)
  assert.match(build, /DeepSeek-Herness\.exe/)
  assert.match(build, /Stop DeepSeek-Herness\.exe/)
  assert.match(build, /DSH-Portable-windows-x64-offline\.zip/)
  assert.match(build, /DSH-Bootstrap\.cs/)
  assert.match(build, /portable-manifest\.json/)
  assert.match(bootstrap, /ZipArchive/)
  assert.doesNotMatch(bootstrap, /tar\.exe/i)
  assert.doesNotMatch(build, /community\.1|DeepSeek Harness\.cmd/)
})

test('Windows setup is a per-user offline installer with durable data outside the app', async () => {
  const setup = await read('installer/windows/DeepSeek-Herness.iss')
  const build = await read('scripts/build-windows.ps1')
  const smoke = await read('scripts/smoke-windows-installer.ps1')
  const verifyRuntime = await read('scripts/verify-runtime.mjs')
  assert.match(setup, /AppId=\{[^}]+\}/)
  assert.match(setup, /OutputBaseFilename=DeepSeek-Herness-Setup/)
  assert.match(setup, /DefaultDirName=\{localappdata\}\\Programs\\DeepSeek-Herness/)
  assert.match(setup, /PrivilegesRequired=lowest/)
  assert.match(setup, /SetupIconFile=.*DSH-Portable\.ico/)
  assert.match(setup, /Name:\s*"\{group\}\\DeepSeek-Herness";[^\n]+IconFilename:\s*"\{app\}\\DeepSeek-Herness\.exe"/)
  assert.match(setup, /Name:\s*"\{group\}\\Stop DeepSeek-Herness";[^\n]+IconFilename:\s*"\{app\}\\Stop DeepSeek-Herness\.exe"/)
  assert.match(setup, /Compression=lzma2\/ultra64/)
  assert.match(setup, /Stop DeepSeek-Herness\.exe/)
  assert.match(setup, /Excludes:\s*"\\data\\\*,\\workspace\\\*"/)
  assert.doesNotMatch(setup, /Excludes:\s*"data\\\*,workspace\\\*"/)
  assert.match(setup, /RunOnceId:\s*"StopDeepSeekHerness"/)
  assert.match(build, /BuildInstaller/)
  assert.match(build, /ISCC/)
  assert.match(build, /subst\.exe/)
  assert.match(build, /InstallerDrive/)
  assert.match(build, /finally[\s\S]+subst\.exe[\s\S]+\/D/)
  assert.match(smoke, /DeepSeek-Herness-Setup\.exe/)
  assert.match(smoke, /DSH_PORTABLE_STATE_ROOT/)
  assert.match(smoke, /unins000\.exe/)
  assert.match(smoke, /\/SP-/)
  assert.match(smoke, /\/NOCANCEL/)
  assert.match(smoke, /\/LOG=/)
  assert.match(smoke, /Get-Content[\s\S]+SetupLog/)
  assert.match(smoke, /dsh-i-/)
  assert.match(smoke, /Invoke-BoundedProcess/)
  assert.match(smoke, /WaitForExit/)
  assert.match(smoke, /LauncherDiagnostic/)
  assert.match(smoke, /WScript\.Shell/)
  assert.match(smoke, /CreateShortcut/)
  assert.match(smoke, /IconLocation/)
  assert.match(smoke, /amazon-bedrock\.json/)
  assert.match(verifyRuntime, /amazon-bedrock\.json/)
  for (const stage of ['Install package', 'Start installed runtime', 'Stop installed runtime', 'Uninstall package']) {
    assert.match(smoke, new RegExp(stage))
  }
})

test('Windows portable self-extractor stays offline, movable, and registration-free', async () => {
  const extractor = await read('installer/windows/DSH-Portable.iss')
  const build = await read('scripts/build-windows.ps1')
  const smoke = await read('scripts/smoke-windows-portable-extractor.ps1')
  const workflow = await read('.github/workflows/ci.yml')

  assert.match(extractor, /AppName=DSH-Portable/)
  assert.match(extractor, /OutputBaseFilename=DSH-Portable-windows-x64-offline/)
  assert.match(extractor, /DefaultDirName=\{src\}\\DSH-Portable/)
  assert.match(extractor, /UsePreviousAppDir=no/)
  assert.match(extractor, /Uninstallable=no/)
  assert.match(extractor, /CreateUninstallRegKey=no/)
  assert.match(extractor, /PrivilegesRequired=lowest/)
  assert.match(extractor, /Compression=lzma2\/ultra64/)
  assert.match(extractor, /Source:\s*"\{#Stage\}\\\*";\s*DestDir:\s*"\{app\}"/)
  assert.doesNotMatch(extractor, /Excludes:/)
  assert.doesNotMatch(extractor, /\[Icons\]|\[Registry\]|installed-mode\.json/i)

  assert.match(build, /DSH-Portable-windows-x64-offline\.exe/)
  assert.match(build, /PortableExtractorSha256/)
  assert.match(build, /installer\\windows\\DSH-Portable\.iss/)
  assert.match(build, /--version/)
  assert.match(build, /Inno Setup 7 or newer/)
  assert.doesNotMatch(build, /Inno Setup 6/)
  assert.match(smoke, /DSH-Portable-windows-x64-offline\.exe/)
  assert.match(smoke, /\/DIR=/)
  assert.match(smoke, /\/DIR="\{0\}"/)
  assert.match(smoke, /\/LOG="\{1\}"/)
  assert.match(smoke, /Start-Process[\s\S]+-ArgumentList \$ExtractorArguments/)
  assert.match(smoke, /\[char\]0x00FC/)
  assert.match(smoke, /installed-mode\.json/)
  assert.match(smoke, /unins\*\.exe/)
  assert.match(smoke, /amazon-bedrock\.json/)
  assert.match(smoke, /runtime\\node\\node\.exe/)
  assert.doesNotMatch(smoke, /&\s+node\s+/)
  assert.match(smoke, /smoke-portable\.mjs/)
  assert.match(workflow, /smoke-windows-portable-extractor\.ps1/)
  assert.match(workflow, /artifacts\/DSH-Portable-windows-x64\.exe/)
  assert.match(workflow, /artifacts\/DSH-Portable-windows-x64\.exe\.sha256/)
  assert.match(workflow, /artifacts\/DSH-Portable-windows-x64-offline\.exe/)
  assert.match(workflow, /artifacts\/portable-manifest\.json/)
})

test('macOS package is a movable signed app shell for both supported architectures', async () => {
  const plist = await read('launcher/macos/Info.plist')
  const app = await read('launcher/macos/DSH-Portable')
  const stop = await read('launcher/macos/Stop DSH-Portable.command')
  const build = await read('scripts/build-macos.sh')

  assert.match(plist, /<string>DSH-Portable<\/string>/)
  assert.match(plist, /<string>io\.github\.wsl043\.dsh-portable<\/string>/)
  assert.match(plist, /<string>DSH-Portable<\/string>\s*<key>CFBundleIconFile<\/key>/s)
  assert.match(app, /Contents\/MacOS/)
  assert.match(app, /runtime\/node\/bin\/node/)
  assert.match(stop, /portable-cli\.mjs" stop/)
  assert.match(build, /darwin-\$ARCH/)
  assert.match(build, /cd "\$STAGE\/app"/)
  assert.doesNotMatch(build, /npm[^\n]+ci --prefix/)
  assert.match(build, /codesign --force --deep --sign -/)
  assert.match(build, /DSH-Portable-macos-\$ARCH\.zip/)
})

test('macOS DMG carries a self-contained app and keeps installed data outside its signature', async () => {
  const installedApp = await read('launcher/macos/DeepSeek-Herness-installed')
  const build = await read('scripts/build-macos.sh')
  assert.match(installedApp, /Contents\/Resources/)
  assert.match(installedApp, /Library\/Application Support\/DeepSeek-Herness/)
  assert.match(installedApp, /DSH_PORTABLE_STATE_ROOT/)
  assert.match(build, /hdiutil create/)
  assert.match(build, /-format ULMO/)
  assert.doesNotMatch(build, /-format ULFO/)
  assert.doesNotMatch(build, /-format UDZO/)
  assert.match(build, /DMG_CREATE_ATTEMPTS/)
  assert.match(build, /for \(\(attempt = 1;/)
  assert.match(build, /rm -f "\$DMG"/)
  assert.match(build, /DeepSeek-Herness-macos-\$ARCH\.dmg/)
  assert.match(build, /Applications/)
  assert.match(build, /codesign --verify --deep --strict/)
})

test('CI executes contracts and real package smoke tests on Windows and both Mac architectures', async () => {
  const workflow = await read('.github/workflows/ci.yml')
  const bootstrapSmoke = await read('scripts/smoke-windows-bootstrap.mjs')
  for (const runner of ['windows-latest', 'macos-15', 'macos-15-intel']) assert.match(workflow, new RegExp(runner))
  assert.match(workflow, /build-windows\.ps1/)
  assert.match(workflow, /build-macos\.sh/)
  assert.match(workflow, /smoke-portable\.mjs/)
  assert.match(workflow, /smoke-windows-bootstrap\.mjs/)
  assert.match(workflow, /tar\.exe -x -f artifacts\/DSH-Portable-windows-x64-offline\.zip/)
  assert.doesNotMatch(workflow, /Expand-Archive/)
  assert.match(workflow, /actions\/checkout@v6/)
  assert.match(workflow, /actions\/setup-node@v6/)
  assert.match(workflow, /actions\/upload-artifact@v6/)
  assert.match(workflow, /innosetup-7\.1\.0-x64\.exe/)
  assert.match(workflow, /0362a383ed217d4c4239b5933866dd96d3eb2102737da92f80f6057a4b40df2f/)
  assert.match(workflow, /Get-FileHash[\s\S]+SHA256/)
  assert.match(workflow, /\/PORTABLE=1/)
  assert.match(workflow, /-IsccPath \$env:ISCC_PATH/)
  assert.doesNotMatch(workflow, /choco install innosetup/)
  assert.match(workflow, /compression-level:\s*0/)
  assert.match(workflow, /if:\s*\$\{\{ always\(\) \}\}/)
  assert.match(bootstrapSmoke, /DSH-Portable-windows-x64\.exe/)
  assert.match(bootstrapSmoke, /中文 空格/)
  assert.match(bootstrapSmoke, /\.dsh-portable-install-/)
  assert.match(bootstrapSmoke, /maxRetries:\s*40/)
  assert.match(bootstrapSmoke, /process\.env\.CI/)
})

test('Node runtime lock covers Windows and both Mac CPU families', async () => {
  const lock = JSON.parse(await read('upstream.lock.json'))
  assert.equal(lock.node.version, '24.19.0')
  assert.match(lock.node.runtimes['win-x64'].archive, /win-x64\.zip$/)
  assert.match(lock.node.runtimes['darwin-arm64'].archive, /darwin-arm64\.tar\.gz$/)
  assert.match(lock.node.runtimes['darwin-x64'].archive, /darwin-x64\.tar\.gz$/)
  for (const runtime of Object.values(lock.node.runtimes)) assert.match(runtime.sha256, /^[0-9a-f]{64}$/)
})
